# ============================================
# PROYECTO FINAL - GitHub Actions CI Template
# ============================================
#
# Pipeline de CI/CD para tu proyecto.
# Ejecuta lint, tests y build en cada push/PR.
#
# Copia este archivo a: .github/workflows/ci.yml
# ============================================

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.13"

jobs:
  # ============================================
  # LINT - Verificar estilo de código
  # ============================================
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Run Ruff linter
        run: uv run ruff check src/ tests/

      - name: Run Ruff formatter check
        run: uv run ruff format --check src/ tests/

  # ============================================
  # TYPE CHECK - Verificar tipos
  # ============================================
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Run Pyright
        run: uv run pyright src/

  # ============================================
  # TEST - Ejecutar tests
  # ============================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]  # Ejecutar después de lint

    # services:
    #   postgres:
    #     image: postgres:17-alpine
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: testdb
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Run tests with coverage
        env:
          DATABASE_URL: sqlite+aiosqlite:///:memory:
          SECRET_KEY: test-secret-key-for-ci-at-least-32-characters
          ENVIRONMENT: testing
        run: |
          uv run pytest tests/ -v --tb=short \
            --cov=src \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=50

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: github.event_name == 'push'
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

  # ============================================
  # BUILD - Construir imagen Docker
  # ============================================
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [test]  # Ejecutar después de tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: task-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================
  # DEPLOY - Desplegar a producción (opcional)
  # ============================================
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     # Ejemplo para Railway
  #     - name: Deploy to Railway
  #       uses: bervProject/railway-deploy@main
  #       with:
  #         railway_token: ${{ secrets.RAILWAY_TOKEN }}
  #         service: task-api
  #
  #     # Ejemplo para Render
  #     # - name: Deploy to Render
  #     #   run: |
  #     #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
